plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace = "app.fjj.p2ptap.core"
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        minSdk = 31

        consumerProguardFiles("consumer-rules.pro")
    }

    buildTypes {
        release {
            // A library is never minified on its own: R8 runs in each app, and
            // only consumer rules reach it. Minifying here would just rename
            // the classes an app then re-renames.
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    // The Go engine AAR. `api` because core compiles against P2PTap directly —
    // for example, TvShellKeeper's bind target is `TvKeeperService` but the
    // engine classes are what make `P2PTapVpnService.isRunning()` type-check,
    // and consumers need them on their compile classpath too.
    //
    // AGP historically refused to let a library depend on a local .aar (the
    // nested AAR would not be packaged into this module's own AAR). Recent AGP
    // 9 accepts this and propagates both the classes.jar and the jni/ native
    // libs through to consuming apps, so mobile and tv no longer each declare
    // the AAR themselves. Regenerated by
    //   p2ptap-core/scripts/build-aar.sh -o bin/p2ptap.aar
    api(files("libs/p2ptap.aar"))

    // api: P2PStateRepository exposes StateFlow, so consumers need coroutines
    // to type-check against it.
    api(libs.androidx.core.ktx)

    testImplementation(libs.junit)
    // Android's local-test org.json classes are stubs; exercise real Go JSON fixtures.
    testImplementation(libs.org.json)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
}
